memory_limit=2048M
max_execution_time=300
max_input_time=300
post_max_size=512M
upload_max_filesize=256M
date.timezone=Europe/Moscow
max_input_vars=10000
display_errors=On
error_reporting=E_ALL
log_errors=On
error_log=/var/log/apache2/php_errors.log