#!/bin/bash
set -eu

mysql --protocol=socket -uroot -p"${MYSQL_ROOT_PASSWORD}" <<-EOSQL
  CREATE USER IF NOT EXISTS '${MYSQL_BITRIX_USER}'@'%' IDENTIFIED BY '${MYSQL_BITRIX_PASSWORD}';
  GRANT ALL PRIVILEGES ON *.* TO '${MYSQL_BITRIX_USER}'@'%';
  FLUSH PRIVILEGES;
EOSQL